sudo: required
matrix:
  fast_finish: true
services:
- docker
before_install:
- docker pull muccg/ccg-composer
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- export "GIT_BRANCH=$TRAVIS_BRANCH"
- test x"$TRAVIS_PULL_REQUEST_BRANCH" != x"" && export "GIT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH" || echo "This build is not a PR."
- export "BRANCH_NAME=$GIT_BRANCH"
- ./travis-build.sh
- ./travis-prodbuild.sh

env:
  global:
    - DOCKER_USERNAME: ccgbuildbot
    - secure: "Pjp0DIjMNYt8YZ9pwpH5He6AM7kT7XF55qh9C+7bwvSYL1GqBcVUokDSGxY+DsdUJAvfivoReTraRXAgxR+ZPce2dGeHsJa1o2HnwCDXgBElI2KTbb4thDsqVpY2O/5I3RxnfzTt8yi3H83O0La/ZXlvtOMbR0mT16gUfqF9aiy8CCrh6qg6X7HHgR/mgTx5xUJp6XSc9VPKE5BxM8n7yrjJolVjEsVZGyA0kTJi8Zxl5DKPExExamE7c2Vj5cN2D6CrtNLgcbkLKESfc0FbUu6FcRtkTBjlBBsZezeEg/wYxCvqwRFHPIPyoG9egnI/cNMMQdtAxHLBtDkX86YXlNZ/Icy8xGvCVMAQEsCRXl5Xs4FdXHUB+XxcDx9CVXmzFB7cHj44TUzigza8Y04fDx/q8G+HrKEELPp5+jDi/NZnXu0HwMvax2Ulo8iKtfk4P1hTIqN5nnx/QSIVZgppLAyijesz8xED/7cwjWo86xK+uvl/iMvRF9NA7+sbqc4X75t6CiWyI17OEdGKsn/YadPpd3Rca7oTiHmYD9UGkzthS/6jU/uZzCJpSVL0bjDTigD8yjp+JoHzooTbmIbvE/UPtjq1OL6+KAGGERJ5I2qv+EsDb9mI/2/BvmbfQ2HbxRPK7Z7BBBxkZrR0vjsyHoe9brXMSQWgYFdO1gyuLcs="
