FROM bioplatformsaustralia/bpaotu
MAINTAINER https://github.com/bioplatformsaustralia/bpaotu

# Project specific deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  libpcre3-dev \
  libpq-dev \
  libssl-dev \
  libyaml-dev \
  libxml2-dev \
  libxslt1-dev \
  libcairo2-dev \
  pkg-config \
  openssh-client \
  zlib1g-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Runtime args, don't re-use build time args
ENV PRODUCTION 0
ENV DEBUG 1

# Strictly speaking not needed as we mount over the top
# However let's make it explicit that we don't want /app from the build image
RUN rm -rf /app && mkdir -p /app

# For dev we use root so we can shell in and do evil things
USER root
WORKDIR /app

RUN env | sort

# Add our python deps in multiple docker layers
# hgvs was failing due to lack of nose, hence the order
COPY ./requirements/dev-requirements.txt /app/bpaotu/
RUN pip install --upgrade -r bpaotu/dev-requirements.txt
COPY ./requirements/test-requirements.txt /app/bpaotu/
RUN pip install --upgrade -r bpaotu/test-requirements.txt
COPY ./requirements/runtime-requirements.txt /app/bpaotu/
RUN pip install --upgrade -r bpaotu/runtime-requirements.txt
COPY ./requirements/biom-requirements.txt /app/bpaotu/
RUN pip install --upgrade -r bpaotu/biom-requirements.txt

# Copy code and install the app
COPY . /app
RUN pip ${PIP_OPTS} install --upgrade -e bpaotu

EXPOSE 8000 9000 9001 9100 9101
VOLUME ["/app", "/data"]

ENV HOME /data
WORKDIR /data

# entrypoint shell script that by default starts runserver
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["runserver_plus"]
