services:
  base:
    build:
      context: ./
      dockerfile: Dockerfile-base
    image: bioplatformsaustralia/bpaotu

  builder:
    build:
      context: ./
      dockerfile: Dockerfile-builder
      args:
        BUILD_VERSION:
        GIT_BRANCH:
    image: bioplatformsaustralia/bpaotu-builder
    network_mode: host

  prod:
    build:
      context: ./
      dockerfile: Dockerfile-prod
      args:
        BUILD_VERSION:
    image: bioplatformsaustralia/bpaotu

  dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: bioplatformsaustralia/bpaotu
