version: '2'
services:

    # data only container pattern
    datadev:
      image: debian:jessie
      volumes:
        - .:/app
        - ./data/dev:/data

    db:
      image: mdillon/postgis:10
      environment:
        - POSTGRES_USER=webapp
        - POSTGRES_PASSWORD=webapp
      ports:
        - "5432"

    cache:
      image: redis:3-alpine

    runserver:
      image: bioplatformsaustralia/bpaotu-dev
      env_file:
        - .env_local
      environment:
        - WAIT_FOR_DB=1
        - WAIT_FOR_CACHE=1

    celeryworker:
      image: bioplatformsaustralia/bpaotu-dev
      command: celery_worker
      env_file:
        - .env_local
      environment:
        - WAIT_FOR_DB=1
        - WAIT_FOR_CACHE=1
