FROM python:3.8-slim
LABEL maintainer https://github.com/BioplatformsAustralia/bpaotu

ENV VIRTUAL_ENV /env
ENV PATH $VIRTUAL_ENV/bin:$PATH
ENV PROJECT_NAME bpaotu
ENV PROJECT_SOURCE https://github.com/BioplatformsAustralia/bpaotu.git
ENV DEPLOYMENT prod
ENV PRODUCTION 1
ENV DEBUG 0
ENV STATIC_ROOT /data/static
ENV WRITABLE_DIRECTORY /data/scratch
ENV MEDIA_ROOT /data/static/media
ENV LOG_DIRECTORY /data/log
ENV MONGO_DB_PREFIX=prod_
ENV DJANGO_SETTINGS_MODULE bpaotu.settings
ENV PYTHONUNBUFFERED 1

RUN addgroup --gid 1000 bioplatforms \
  && adduser --disabled-password --home /data --no-create-home --system -q --uid 1000 --ingroup bioplatforms bioplatforms \
  && mkdir /data /app \
  && chown bioplatforms:bioplatforms /data

RUN apt-get update && apt-get install -y --no-install-recommends \
  gettext \
  libpcre3 \
  libpq5 \
  gdal-bin \
  libgeos3.11.1 \
  libproj-dev \
  ncbi-blast+ \
  mime-support \
  unixodbc \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python3 -m venv $VIRTUAL_ENV

ENTRYPOINT ["/bin/sh"]
