# Container used to build bpaotu
FROM bioplatformsaustralia/bpaotu-base
MAINTAINER https://github.com/bioplatformsaustralia/bpaotu

ARG BUILD_VERSION
ARG GIT_BRANCH

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  libpcre3-dev \
  libpq-dev \
  libssl-dev \
  libyaml-dev \
  libxml2-dev \
  libxslt1-dev \
  pkg-config \
  openssh-client \
  zlib1g-dev \
  curl \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
ENV POETRY_PATH /root/.local/bin
ENV PATH ${VIRTUAL_ENV}/bin:${POETRY_PATH}:$PATH
RUN poetry --version

ENV WORKINGDIR /data/app
WORKDIR ${WORKINGDIR}

ENV PYTHON_PIP_VERSION 21.1.3
RUN . ${VIRTUAL_ENV}/bin/activate && pip install --upgrade pip==$PYTHON_PIP_VERSION

RUN git clone --depth=1 --recurse-submodules --branch="${GIT_BRANCH}" "${PROJECT_SOURCE}" ${WORKINGDIR}
RUN git rev-parse HEAD | tee .version

RUN pip install --upgrade -r requirements/runtime-requirements.txt \
&& pip install --upgrade -r requirements/biom-requirements.txt \
&& cd "${WORKINGDIR}/${PROJECT_NAME}" && pip install . \
&& cd "${WORKINGDIR}/bpa-ingest" && poetry install

ADD build/frontend.tgz /data/app/bpaotu/bpaotu/static/bpaotu

WORKDIR /data

ENV ARTIFACTS env \
    app/docker-entrypoint.sh \
    app/uwsgi \
    app/${PROJECT_NAME}
ENV TARBALL "/data/${PROJECT_NAME}-${BUILD_VERSION}.tar"
ENV TAR_OPTS --exclude-vcs \
    --exclude=app/bpaotu/bpaotu/frontend/* \
    --verify \
    --checkpoint=1000 \
    --checkpoint-action=dot \
    --create \
    --preserve-permissions

RUN rm -rf env && cp -rp /env .
RUN rm -f "${TARBALL}" && tar ${TAR_OPTS} -f "${TARBALL}" ${ARTIFACTS}
RUN rm -f "${TARBALL}.gz" && gzip "${TARBALL}"

RUN rm -rf /env && rm -rf /data/app && rm -rf /data/env

VOLUME ["/data"]

CMD ["-c", "cp ${TARBALL}.gz /tmp"]
