version: '2'
services:

    dbprod:
      extends:
        file: docker-compose-common.yml
        service: db
      networks:
       default:
         aliases:
           - dbtest

    cacheprod:
      extends:
        file: docker-compose-common.yml
        service: cache
      networks:
       default:
         aliases:
           - cachetest

    nginxprod:
      extends:
        file: docker-compose-common.yml
        service: nginx
      depends_on:
        - uwsgiprod
      networks:
       default:
         aliases:
           - nginxtest

    celeryworker:
      extends:
        file: docker-compose-common.yml
        service: celeryworker
      volumes:
        - uwsgi-prod-data:/data
      depends_on:
        - dbprod
        - cacheprod

    uwsgiprod:
      image: bioplatformsaustralia/bpaotu:${BUILD_VERSION}
      command: uwsgi_local
      environment:
        - DEBUG=0
        - WAIT_FOR_DB=1
        - WAIT_FOR_CACHE=1
        - ALLOWED_HOSTS=*
        - CSRF_TRUSTED_ORIGINS=localhost nginxtest
        - CACHESERVER=cacheprod
        - DBSERVER=dbprod
      volumes:
        - uwsgi-prod-data:/data
      depends_on:
        - dbprod
        - cacheprod
      networks:
       default:
         aliases:
           - uwsgitest
           - uwsgi

volumes:
  uwsgi-prod-data:
