FROM continuumio/miniconda3

# Create dedicated conda environment for celery worker and set it as default
COPY environment-celery.yml .
RUN conda env create -f environment-celery.yml && conda clean --all --yes
ENV PATH=/opt/conda/envs/celeryenv/bin:$PATH

# Activate the environment and install pip-only packages
# TODO: move all this to environment-celery.yml
COPY requirements/celery-requirements.txt .
RUN /bin/bash -c "source activate celeryenv && pip install --no-cache-dir -r celery-requirements.txt"

# Use this to set the default conda environoment for an interactive shell
RUN echo "source /opt/conda/etc/profile.d/conda.sh && conda activate celeryenv" >> /root/.bashrc

# Set working directory so bpaotu app is available
WORKDIR /app
COPY . /app

# Notes:
# Don't set HOME to /app because other containers used /data as home

# Run the celery worker for bpaotu when container starts
CMD ["celery", "-A", "bpaotu", "worker", "--loglevel=info"]
