FROM bioplatformsaustralia/bpaotu
LABEL maintainer=https://github.com/bioplatformsaustralia/bpaotu

ARG BUILD_VERSION

RUN mkdir -p /data \
    && /bin/chown bioplatforms:bioplatforms /data

ADD build/${PROJECT_NAME}-${BUILD_VERSION}.tar.gz /

EXPOSE 9100 9101
VOLUME ["/data"]

# Drop privileges, set home for bioplatforms
USER bioplatforms
ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["uwsgi"]
