FROM continuumio/miniconda3

# Optimised conda env for celery
COPY environment-celery.yml .

# Create conda environment from YAML
RUN conda env create -f environment-celery.yml && conda clean --all --yes

# Activate the environment and install pip-only packages
COPY requirements/celery-requirements.txt .
RUN /bin/bash -c "source activate celeryenv && pip install --no-cache-dir -r celery-requirements.txt"

# Set the conda env as default
ENV PATH=/opt/conda/envs/celeryenv/bin:$PATH

# Set working directory and copy only what you need
WORKDIR /app
COPY . .

# Optional: Activate it by default for interactive shells (if needed)
# SHELL ["conda", "run", "-n", "celeryenv", "/bin/bash", "-c"]

# Default command for Celery worker
CMD ["celery", "-A", "bpaotu", "worker", "--loglevel=info"]
