FROM continuumio/miniconda3

# System packages
RUN apt-get update && apt-get install -y --no-install-recommends \
  ncbi-blast+ \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create dedicated conda environment for celery worker and set it as default
COPY environment-celery.yml .
RUN conda env create -f environment-celery.yml && conda clean --all --yes
ENV PATH=/opt/conda/envs/celeryenv/bin:$PATH

# This sets the default conda envirnoment for an interactive shell
# Note: these lines are also needed in the entrypoint function
RUN echo "source /opt/conda/etc/profile.d/conda.sh && conda activate celeryenv" >> /root/.bashrc

# uid and gid must match runserver Dockerfile
RUN addgroup --gid 1000 bioplatforms \
  && adduser --disabled-password --home /data --no-create-home --system -q --uid 1000 --ingroup bioplatforms bioplatforms \
  && mkdir /data /app \
  && chown bioplatforms:bioplatforms /data

# Copy and set working directory so app is available
WORKDIR /app
COPY . /app

# Ensure worker entrypoint script is executable
RUN chmod +x /app/docker-worker-entrypoint.sh

# Notes:
# Don't set HOME to /app because other containers used /data as home

# Switch to non-root user
USER bioplatforms

# Run the celery worker when container starts
# Default CMD provided for docker compose (puppet runs command explicitly)
ENTRYPOINT ["/app/docker-worker-entrypoint.sh"]
CMD ["celery_worker"]
