services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    read_only: false
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    tmpfs:
      - /node_modules

  runserver:
    image: bioplatformsaustralia/bpaotu:dev
    env_file:
      - .env_local
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CACHE=1
    volumes:
      - .:/app
      - ./data/dev:/data
    ports:
      - "8080:8080" # Development mode port (runserver)
      - "8888:8888" # Jupyter Notebook port (for development/debugging)
    depends_on:
      - db
      - cache

  celeryworker:
    image: bioplatformsaustralia/bpaotu-worker
    env_file:
      - .env_local
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CACHE=1
      - PYTHONPATH=/app/bpaotu
      - DJANGO_SETTINGS_MODULE=bpaotu.settings_celery
    volumes:
      # - .:/app
      - ./data/dev:/data
    depends_on:
      - db
      - cache
      - runserver

volumes:
  dbdata:
