# note that while docker passes the .env file env variables through automatically
# we have kept them in below to be explicit

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-webapp}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-webapp}
      - POSTGRES_DB=${POSTGRES_DB:-webapp}
    command:
      - "postgres"
      - "-c"
      - "wal_level=minimal"
      - "-c"
      - "max_wal_size=10GB"
      - "-c"
      - "max_wal_senders=0"
    shm_size: 1gb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/

  cache:
    image: redis:8-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  runserver:
    image: bioplatformsaustralia/bpaotu:dev
    env_file:
      - .env_local
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CACHE=1
    volumes:
      # bind-mount the backend source code in development to allow hot reloading of changes to the Django app
      - .:/app
      - ./data/dev:/data
      - /data/MAGS:/data/MAGS
    ports:
      - "8080:8080" # Development mode port (runserver)
      - "8888:8888" # Jupyter Notebook port (for development/debugging)
    depends_on:
      - db
      - cache

  celeryworker:
    image: bioplatformsaustralia/bpaotu-worker
    env_file:
      - .env_local
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CACHE=1
      - PYTHONPATH=/app/bpaotu
      - DJANGO_SETTINGS_MODULE=bpaotu.settings_celery
    volumes:
      # - .:/app
      - ./data/dev:/data
    depends_on:
      - db
      - cache
      - runserver

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    read_only: false
    volumes:
      # bind mount the frontend source code for development to allow hot reloading of changes to the React app
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    tmpfs:
      - /node_modules

volumes:
  dbdata:
