FROM python:3.8-slim
LABEL maintainer https://github.com/BioplatformsAustralia/bpaotu

ENV VIRTUAL_ENV /env
ENV PATH $VIRTUAL_ENV/bin:$PATH
ENV PROJECT_NAME bpaotu
ENV PROJECT_SOURCE https://github.com/BioplatformsAustralia/bpaotu.git
ENV DEPLOYMENT prod
ENV PRODUCTION 1
ENV DEBUG 0
ENV STATIC_ROOT /data/static
ENV WRITABLE_DIRECTORY /data/scratch
ENV MEDIA_ROOT /data/static/media
ENV LOG_DIRECTORY /data/log
ENV MONGO_DB_PREFIX=prod_
ENV DJANGO_SETTINGS_MODULE bpaotu.settings
ENV PYTHONUNBUFFERED 1

RUN addgroup --gid 1000 bioplatforms \
  && adduser --disabled-password --home /data --no-create-home --system -q --uid 1000 --ingroup bioplatforms bioplatforms \
  && mkdir /data /app \
  && chown bioplatforms:bioplatforms /data

RUN apt-get update
RUN apt-get install -y --no-install-recommends gettext
RUN apt-get install -y --no-install-recommends libpcre3
RUN apt-get install -y --no-install-recommends libpq5
RUN apt-get install -y --no-install-recommends gdal-bin
RUN apt-get install -y --no-install-recommends libgeos3.11.1
RUN apt-get install -y --no-install-recommends libproj-dev
RUN apt-get install -y --no-install-recommends ncbi-blast+
RUN apt-get install -y --no-install-recommends mime-support
RUN apt-get install -y --no-install-recommends unixodbc
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN python3 -m venv $VIRTUAL_ENV

ENTRYPOINT ["/bin/sh"]
