# note that on server we use the specific version tags
# but for local testing we can use the :prod tag which is built from the prod target in the Dockerfile
# (worker is the same for both prod and dev)

services:
  frontend:
    image: bioplatformsaustralia/bpaotu:frontend
    ports:
      # For local testing, 4000 is used as the HTTP port and 4443 is used as the HTTPS port with self-signed certs
      # (Note: the container nginx config redirect from 4000 will be to 443, not 4443, so while redirecting will happen, need to specify 4443 manually in browser)
      - "4000:80"
      - "4443:443"
    depends_on:
      - runserver
    volumes:
      - ./certs:/etc/nginx/certs:ro
    read_only: true
    tmpfs:
      - /tmp

  runserver:
    image: bioplatformsaustralia/bpaotu:prod
    env_file:
      - .env_local # for local HTTP-only testing
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CACHE=1
    volumes:
      - ./data/prod:/data
    depends_on:
      - db
      - cache

  celeryworker:
    image: bioplatformsaustralia/bpaotu-worker
    env_file:
      - .env_local # for local HTTP-only testing
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CACHE=1
      - PYTHONPATH=/app/bpaotu
      - DJANGO_SETTINGS_MODULE=bpaotu.settings_celery
    volumes:
      - ./data/prod:/data
    depends_on:
      - db
      - cache
      - runserver

volumes:
  dbdata:
