version: '2'
services:

  base:
    build:
      context: ./
      dockerfile: Dockerfile-base
      args:
        http_proxy:
    image: muccg/bpaotu-base

  builder:
    build:
      context: ./
      dockerfile: Dockerfile-builder
      args:
        http_proxy:
    image: muccg/bpaotu-builder
    command: releasetarball
    network_mode: host
    environment:
        BUILD_VERSION:
        GIT_BRANCH:
        PIP_INDEX_URL:
        PIP_TRUSTED_HOST:
        NO_PROXY:
    volumes:
      - ./build:/data

  node:
    build:
       context: ./
       dockerfile: Dockerfile-node
    image: muccg/bpaotu-node
    working_dir: /data/app/bpaotu/bpaotu/frontend
    command: build
    environment:
        YARN_CACHE_FOLDER: /opt/yarn_cache
    volumes:
      - ./build:/data
      - ./yarn_cache:/opt/yarn_cache

  dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        ARG_PIP_INDEX_URL: ${PIP_INDEX_URL}
        ARG_PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        http_proxy:
    image: muccg/bpaotu-dev
    volumes:
      - .:/app

  prod:
    build:
      context: ./
      dockerfile: Dockerfile-prod
      args:
        ARG_BUILD_VERSION: ${BUILD_VERSION}
    image: muccg/bpaotu:${BUILD_VERSION}

  lint:
    image: muccg/linter:python3
    working_dir: /app/bpaotu
    volumes:
      - ./:/app
    command:
      - flake8
