# bpaotu production
FROM bioplatformsaustralia/bpaotu-base
MAINTAINER https://github.com/bioplatformsaustralia/bpaotu

ARG ARG_BUILD_VERSION

ENV BUILD_VERSION $ARG_BUILD_VERSION

RUN env | sort

RUN mkdir -p /data \
    && /bin/chown bioplatforms:bioplatforms /data

ADD build/${PROJECT_NAME}-${BUILD_VERSION}.tar.gz /

EXPOSE 9100 9101
VOLUME ["/data"]

# Drop privileges, set home for bioplatforms
USER bioplatforms
ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["uwsgi"]
