FROM muccg/python-base:3.7-debian-9
MAINTAINER https://github.com/muccg/bpaotu

ENV PROJECT_NAME bpaotu
ENV PROJECT_SOURCE https://github.com/muccg/bpaotu.git
ENV DEPLOYMENT prod
ENV PRODUCTION 1
ENV DEBUG 0
ENV STATIC_ROOT /data/static
ENV WRITABLE_DIRECTORY /data/scratch
ENV MEDIA_ROOT /data/static/media
ENV LOG_DIRECTORY /data/log
ENV MONGO_DB_PREFIX=prod_
ENV DJANGO_SETTINGS_MODULE bpaotu.settings

RUN env | sort

# Project specific deps
RUN apt-get update && apt-get install -y --no-install-recommends \
  gettext \
  libpcre3 \
  libpq5 \
  gdal-bin \
  libgeos-3.5.1 \
  libproj-dev \
  ncbi-blast+ \
  mime-support \
  unixodbc \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/sh"]
