services:
  prod:
    build:
      context: .
      target: prod
      args:
        BUILD_VERSION: ${BUILD_VERSION:-dev}
    image: bioplatformsaustralia/bpaotu:prod

  dev:
    build:
      context: .
      target: dev
    image: bioplatformsaustralia/bpaotu:dev

  worker:
    build:
      context: .
      target: worker
    image: bioplatformsaustralia/bpaotu-worker

  frontend:
    build:
      context: ./frontend
      target: prod
    image: bioplatformsaustralia/bpaotu-frontend:prod

  frontend-dev:
    build:
      context: ./frontend
      target: dev
    image: bioplatformsaustralia/bpaotu-frontend:dev
