name: celeryenv
channels:
  - conda-forge
dependencies:
  ## core functionality
  - python=3.9
  - gdal=3.11.3
  - numpy=1.26.4
  - pandas=2.3.1
  - scipy=1.13.1
  - numba=0.60.0
  - celery=5.5.3
  ## task related
  - matplotlib==3.8.3
  ## packages only available via pip
  - pip
  - pip:
      ## core functionality:
      # django and sqlalchemy
      - Django==2.2.10
      - django-redis==4.10.0
      - redis==3.4.1 # included by django-redis, but specify version
      - SQLAlchemy==1.3.16
      - SQLAlchemy-Utils==0.41.1
      - sqlalchemy-citext==1.6.post1
      # settings env config
      - ccg-django-utils
      # logging
      - colorlog==4.1.0
      # debugging memory usage
      - psutil
      # need this binary rather than conda package
      # (which builds and relies on correct system libraries)
      - psycopg2-binary==2.9.9
      ## task related:
      # periodic ckan update
      - git+https://github.com/BioplatformsAustralia/ckanapi.git@streaming-uploads
      # biom
      - zipstream==1.1.4
      # blast
      - basemap==1.4.1
      # comparison
      - fastdist==1.1.6
      - umap-learn==0.5.7
      - fastparquet==0.8
      - pyarrow==8
      # galaxy
      - requests==2.32.4
