# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_name', models.CharField(max_length=300)),
                ('import_result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
