# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 08:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOntologyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('ontology_name', models.CharField(max_length=300)),
                ('import_result', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'ordering': ['project_name', 'ontology_name'],
            },
        ),
    ]
