# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOntologyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_filename', models.CharField(max_length=300)),
                ('ontology_name', models.CharField(max_length=300)),
                ('import_result', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ontology_filename', 'ontology_name'],
            },
        ),
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
