# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0002_importsamplesmissingmetadatalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importontologylog',
            options={'ordering': ['environment', 'ontology_name']},
        ),
        migrations.RenameField(
            model_name='importontologylog',
            old_name='project_name',
            new_name='environment',
        ),
    ]
