# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0003_auto_20180305_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=300)),
                ('file_size', models.BigIntegerField()),
                ('rows_imported', models.BigIntegerField()),
                ('rows_skipped', models.BigIntegerField()),
            ],
        ),
    ]
