# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0004_importfilelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfilelog',
            name='filename',
            field=models.CharField(default=None, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
