# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0005_importfilelog_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importfilelog',
            options={'ordering': ['file_type', 'filename']},
        ),
        migrations.RemoveField(
            model_name='importfilelog',
            name='id',
        ),
        migrations.AlterField(
            model_name='importfilelog',
            name='filename',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
