# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0006_auto_20180310_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodology', models.CharField(max_length=32)),
                ('revision_date', models.DateField()),
                ('imported_at', models.DateTimeField()),
                ('uuid', models.CharField(max_length=36)),
            ],
        ),
    ]
