# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0007_importmetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importontologylog',
            old_name='import_result',
            new_name='invalid_values',
        ),
        migrations.AddField(
            model_name='importmetadata',
            name='otu_count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importmetadata',
            name='samplecontext_count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importmetadata',
            name='sampleotu_count',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
