# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0008_auto_20181124_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmetadata',
            name='imported_at',
            field=models.DateField(),
        ),
    ]
