# Generated by Django 2.2.8 on 2020-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0011_auto_20200121_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsamplesmissingmetadatalog',
            name='reason',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
