# Generated by Django 2.2.8 on 2020-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0012_auto_20200121_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDenoisedDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_sequence', models.TextField()),
                ('taxonomy_string', models.TextField()),
                ('amplicon', models.TextField()),
                ('email', models.TextField()),
                ('selected_samples', models.TextField()),
            ],
        ),
    ]
