# Generated by Django 2.2.8 on 2020-01-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0013_nondenoiseddatarequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportFileLog',
        ),
        migrations.DeleteModel(
            name='ImportMetadata',
        ),
        migrations.DeleteModel(
            name='ImportOntologyLog',
        ),
        migrations.DeleteModel(
            name='ImportSamplesMissingMetadataLog',
        ),
    ]
