# Generated by Django 2.2.10 on 2022-12-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bpaotu', '0015_metagenomerequest'), ('bpaotu', '0016_auto_20221205_1044')]

    dependencies = [
        ('bpaotu', '0014_auto_20200124_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetagenomeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sample_ids', models.TextField()),
                ('file_types', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
