# Generated by Django 3.2.25 on 2026-07-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaotu', '0015_metagenomerequest_squashed_0016_auto_20221205_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagenomerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nondenoiseddatarequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
